# Generated by Django 2.0 on 2017-12-21 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20171221_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionanswer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 7, 58, 15, 483617, tzinfo=utc)),
        ),
    ]
