# Generated by Django 2.0 on 2017-12-21 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_userquestionanswer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionanswer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 7, 58, 55, 752695, tzinfo=utc)),
        ),
    ]
